### PR TITLE
Added simple authorization for secure login.

### PR DESCRIPTION
**Pull request by szbk**
When running the application on the remote server, I added simple authorization to prevent others from logging in.

### CODE REVIEW

**Comment by arunbandari** [comment]
@szbk Thanks for the PR.
This looks good, but can we make this optional? I mean, if USERNAME and PASSWORD are not defined in the env, then we should directly be able to access the site.

**Comment by szbk** [comment]
You are right. Some may not want to use it. Especially locally I will edit and send again, is it ok?

**Comment by arunbandari** [comment]
> You are right. Some may not want to use it. Especially locally I will edit and send again, is it ok?

Yes @szbk, it would be great if you modify the code accordingly.

**Comment by szbk** [comment]
I have optionally revised the user name and password prompt. ⚡️

**Comment by arunbandari** [comment]
@szbk will you be able to add some details about this feature to the readme, like how to setup and how to disable it?

**Comment by szbk** [comment]
I added the authentication directive in README.md 🔥

**Review by arunbandari — APPROVED** [review]

**Pull request merged**
